Data Access in Python/curs1/djproject/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


app_name = "blog"
urlpatterns = [
    path('all/', blog_list_view),
    # Aici e greseala -> trebuia adaugat name="blog_details_view"
    path('<slug>/', blog_details_view, name="blog_details_view")
]

Data Access in Python/curs1/djproject/cart/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = "cart"
urlpatterns = [
    path('', cart_view, name="cart_details"),
    path('clearcart/', clear_cart_view, name="clear"),
    path('addtocart/', add_product_to_cart_view, name="add")
   
]

Data Access in Python/curs1/djproject/djproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
    path('store/', include('store.urls',namespace='store')),
    path('cart/', include('cart.urls',namespace='cart')),
    path('', include('profileapp.urls',namespace='profileapp'))
]

Data Access in Python/curs1/djproject/profileapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


app_name = 'profileapp'

urlpatterns = [
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  
    path('accounts/profile/', profile_view)
]

Data Access in Python/curs1/djproject/store/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

from django.contrib.sitemaps.views import sitemap as view
# from django.contrib.sites import sitemaps
from store.sitemaps import ProductSitemap

app_name = "store"
urlpatterns = [
    path('categories/', store_list_view),
    path('jsonproducts/', jsonproducts_view),
    path('csvproducts/', csvproducts_view),
    path('pdfproducts/', pdfproducts_view),
     path('xmlhardcodat/', xml_view),
     path('sitemap.xml/', view, {'sitemaps': {'products':ProductSitemap, }},
     name="django.contrib.sitemaps.views"),
    path('testcookie/', cookie_view),
    path('testsession/', session_view),
    # Aici e greseala -> trebuia adaugat name="store_details_view"
    path('<slug>/', store_details_view, name="store_details_view"),
    # 
    
    
]

Data Access in Python/curs1/djproject/blog/models.py
from django.db import models
from django.shortcuts import reverse
# Create your models here.



class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField()
    created_date = models.DateField(auto_now=True)
    STATUS_CHOICES = ( ('draft', 'Draft'), ('published', 'Published') )
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='draft')
    
    def __str__(self):
        return self.title

    def generate_slug(self):
        return reverse('blog:blog_details_view', args=[self.slug])

Data Access in Python/curs1/djproject/cart/models.py
from django.db import models

# Create your models here.

Data Access in Python/curs1/djproject/profileapp/models.py
from django.db import models

# Create your models here.

Data Access in Python/curs1/djproject/store/models.py
from django.db import models
from django.shortcuts import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)



    def get_absolute_url(self):
        return reverse('store:store_details_view', args=[self.slug])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product'
        ordering = ('category','name')

Data Access in Python/curs1/djproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.

def blog_list_view(request):
    print(request.GET.get("search"))
    search = request.GET.get("search")
    if search:
        posts = Post.objects.filter(title__contains=search) 
    else:
        posts =  Post.objects.all()
    return render(request, 'blog_list.html', {'posts':posts})

def blog_details_view(request, slug):
    post_details = get_object_or_404(Post, slug=slug)
    return render(request, 'blog_details.html', {'post': post_details})

Data Access in Python/curs1/djproject/cart/views.py
from django.shortcuts import render, redirect
from .cart import Cart
# Create your views here.
from store.models import Product

def cart_view(request):
  
    current_cart = Cart(request)
    nr_produse = len(current_cart)

    products_dict = current_cart.products
    products =  Product.objects.filter(pk__in=products_dict.keys())

    print(nr_produse)
    context = {'nr_produse':nr_produse,
    'products':products}
    return render(request, 'cart.html', context)


def clear_cart_view(request):
    current_cart = Cart(request)
    current_cart.clear_cart()
    return redirect('cart:cart_details')


def add_product_to_cart_view(request):
    current_cart = Cart(request)
    current_cart.add_product(1, 1)
    return redirect('cart:cart_details')

Data Access in Python/curs1/djproject/profileapp/views.py
from django.shortcuts import render

# Create your views here.

def profile_view(request):
    return render(request, 'profile.html')

Data Access in Python/curs1/djproject/store/views.py
import csv
import weasyprint
from django.shortcuts import render, get_object_or_404
from .models import Product
from django.http import JsonResponse, HttpResponse
# Create your views here.
# from cart.cart import Cart

def store_list_view(request):
    print(request.GET.get("search"))
    search = request.GET.get("search")
    if search:
        products = Product.objects.filter(title__contains=search) 
    else:
        products =  Product.objects.all()
    return render(request, 'store_list.html', {'products':products})

def store_details_view(request, slug):
    # Cart(request)
    product_details = get_object_or_404(Product, slug=slug)
    return render(request, 'store_details.html', {'product': product_details})
 
def jsonproducts_view(request):
    products =  list(Product.objects.all())
    products = [ {"nume":product.name, "pret":product.price}   for product in products  ]
    return JsonResponse({"products": products})


def csvproducts_view(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] =  'attachment; filename="products.csv"'
    writer = csv.writer(response)
    writer.writerow(('Titlu', 'Slug', 'Pret', 'Description'))
    products =  list(Product.objects.all())
    for prod in products:
        writer.writerow((prod.name, prod.slug, prod.price, prod.description))
    return response


def pdfproducts_view(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] =  'attachment; filename="products.pdf"'

    
    html_string = ""
    products =  list(Product.objects.all())
    for prod in products:
        html_string += f"<h1>{prod.name} - {prod.price} </h1>"

    weasyprint.HTML(string=html_string).write_pdf(response)
    return response


def xml_view(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] =  'attachment; filename="products.pdf"'

    
    html_string = ""
    products =  list(Product.objects.all())
    for prod in products:
        html_string += f"<h1>{prod.get_absolute_url()} </h1>"

    weasyprint.HTML(string=html_string).write_pdf(response)
    return response


def cookie_view(request):

    print("cookies:", request.COOKIES)


    response = HttpResponse('Ai o prajitura')
    # response.set_cookie('cheie', 'valoare')
    request.COOKIES['noua_cheie_cookie'] = 'valoare'
    return response

def session_view(request):
    request.session['cheie_sesiune'] = 'valoare_sesiune'
    response = HttpResponse('Ai o sesiune')
    return response

Data Access in Python/curs1/djproject/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blogul nostru frumos</title>
</head>
<body>
    
    {% block mainblock %}
         <h1> Mainblock din base </h1>
    {% endblock mainblock %}

    <p> Intre blocuri gri</p>

    {% block endblock %}

       
    {% endblock endblock %}
    
</body>
</html>

Data Access in Python/curs1/djproject/blog/templates/blog_details.html
{% extends "base.html" %}
{% block mainblock %}

{% endblock mainblock %}

Data Access in Python/curs1/djproject/blog/templates/blog_list.html
{% extends "base.html" %}
{% block mainblock %}

     <h1> Mainblock din blog_list </h1>

    {% for post in posts  %}
    <a href="{{ post.generate_slug }}">
            <h3> {{ post.title }} </h3>
    </a>

        <p> {{ post.description }} </p>
    {% endfor %}

{% endblock mainblock %}

Data Access in Python/curs1/djproject/cart/templates/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if nr_produse %}
         <h1> Aveti {{nr_produse}} de produse in cart </h1>

        {% for product in products   %}
           <h3> {{ product.name }} </h3>  
        {% endfor %}


    {% else %}
         <h1> Nu aveti nimic in cart </h1>
    {% endif %}

    <form action="{% url "cart:clear" %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Empty Cart">
    </form>
    

</body>
</html>

Data Access in Python/curs1/djproject/profileapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aplicatia noastra de todo</title>
</head>
<body>
   

      {% block mainblock %}
      
      {% endblock mainblock %}
    
</body>
</html>

Data Access in Python/curs1/djproject/profileapp/templates/django_registration/activation_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>  Account successfully ACTIVATED </h1>

    <a href="{% url 'home' %}">Catre site</a>
    
</body>
</html>

Data Access in Python/curs1/djproject/profileapp/templates/django_registration/registration_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>  Account successfully created </h1>

    <p>  Please check out your email</p>
</body>
</html>

Data Access in Python/curs1/djproject/profileapp/templates/django_registration/registration_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Create account </h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form }} 
        <input type="submit" value="Create Account">
    </form>


</body>
</html>

Data Access in Python/curs1/djproject/profileapp/templates/profile.html
{% extends "base.html" %}

{% block mainblock %}
      
   


{% endblock mainblock %}

Data Access in Python/curs1/djproject/store/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blogul nostru frumos</title>
</head>
<body>
    
    {% block mainblock %}
         <h1> Mainblock din base </h1>
    {% endblock mainblock %}



    {% block endblock %}

       
    {% endblock endblock %}
    
</body>
</html>

Data Access in Python/curs1/djproject/store/templates/store_details.html
{% extends "base.html" %}
{% block mainblock %}

    <h1> {{ product.name }}</h1>
    <p> {{ product.price }} RON </p>

     <form action="{% url "cart:add" %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Add To Cart">
    </form>

{% endblock mainblock %}

Data Access in Python/curs1/djproject/store/templates/store_list.html
{% extends "base.html" %}
{% block mainblock %}

     <h1> Mainblock din store_list </h1>

    {% for product in products  %}
    <a href="{{ product.get_absolute_url }}">
            <h3> {{ product.name }} </h3>
    </a>

        <p> {{ product.description }} </p>
    {% endfor %}

{% endblock mainblock %}